import {EmbedBuilder} from "discord.js"

export const footer = "Activity Color Bot © Philainel, 2022"
export const ErrorEmbed = (comment = "Произошла непредвиденная ошибка.") => new EmbedBuilder()
	.setColor('#c62828')
	.setTitle(':no_entry: Error!')
	.setDescription(comment)
	.setTimestamp(Date.now())
	.setFooter({text: footer})
export const DangerousEmbed = (comment: string) => new EmbedBuilder()
	.setColor('#c62828')
	.setTitle('**:warning: Warning!**')
	.setDescription(comment)
	.setTimestamp(Date.now())
	.setFooter({text: footer})
export const SuccesfulEmbed = (comment = "Команда успешно выполнено.") => new EmbedBuilder()
	.setColor('#3ba55d')
	.setTitle(':white_check_mark: Success!')
	.setDescription(comment)
	.setTimestamp(Date.now())
	.setFooter({text: footer})
export const ProcessingEmbed = (comment = "Действие выполняется...") => new EmbedBuilder()
	.setColor("Yellow")
	.setTitle(":clock2: Running...")
	.setDescription(comment)
	.setTimestamp(Date.now())
	.setFooter({text: footer})
export const InfoEmbed = (title: string, comment = "") => new EmbedBuilder()
	.setColor("DarkGrey")
	.setTitle(':information_source:' + title)
	.setDescription(comment)
	.setTimestamp(Date.now())
	.setFooter({text: footer})